// ==MiruExtension==
// @name         HDGharTV
// @version      v0.0.9
// @author       OshekharO
// @lang         hi
// @license      MIT
// @package      hdghartv
// @type         bangumi
// @icon         https://hdghartv.cc/favicon.ico
// @webSite      https://hdghartv.cc
// @nsfw         false
// ==/MiruExtension==

const SITE_URL = "https://hdghartv.cc";
const API_URL = `${SITE_URL}/api`;
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

export default class extends Extension {
  async latest(page = 1) {
    const pageNumber = Number(page) > 0 ? Number(page) : 1;
    const sitePath = pageNumber > 1 ? `/page/${pageNumber}/` : "/";
    const scraped = this.scrapeCatalog(await this.sitePage(sitePath));
    if (scraped.length) return scraped;

    const endpoints = [
      `/movies/public?page=${pageNumber}&limit=24`,
      `/movies?page=${pageNumber}&limit=24`,
      `/trending?page=${pageNumber}&limit=24`,
    ];

    for (const endpoint of endpoints) {
      const data = await this.api(endpoint);
      const movies = this.catalogItems(data);
      if (movies.length) return await this.toSearchResults(movies);
    }

    // The public API currently documents search rather than a catalogue
    // endpoint. This keeps the home tab useful if the list endpoint is absent.
    return this.search("a", pageNumber);
  }

  async search(kw, page = 1) {
    const query = String(kw || "").trim();
    if (!query) return [];

    const encoded = encodeURIComponent(query);
    const sitePaths = [
      `/search?q=${encoded}`,
      `/?s=${encoded}`,
    ];
    for (const sitePath of sitePaths) {
      const scraped = this.scrapeCatalog(await this.sitePage(sitePath));
      if (scraped.length) return scraped;
    }

    const data = await this.api(`/search?q=${encoded}`);
    const items = [
      ...(Array.isArray(data && data.movies) ? data.movies : []).map((item) => ({
        ...item,
        mediaType: "movie",
      })),
      ...(Array.isArray(data && data.series) ? data.series : []).map((item) => ({
        ...item,
        mediaType: "series",
      })),
    ];

    return await this.toSearchResults(items);
  }

  async detail(url) {
    const [mediaType, id] = String(url || "").split(":");
    if (!id || !/^(movie|series)$/.test(mediaType)) {
      throw new Error("HDGharTV: invalid catalogue item URL.");
    }

    const pageUrl = `${SITE_URL}/${mediaType}/${encodeURIComponent(id)}`;
    const scraped = this.scrapeDetail(await this.sitePage(pageUrl), pageUrl);
    if (scraped && scraped.episodes.length) return scraped;

    const data = await this.api(
      `/${mediaType === "series" ? "series" : "movies"}/public/${encodeURIComponent(id)}`
    );
    if (!data || typeof data !== "object") {
      throw new Error("HDGharTV: unable to load the movie details.");
    }

    const title = this.cleanText(data.title || data.name || "HDGharTV");
    const cover = this.imageValue(data);
    const desc = this.cleanText(
      data.description || data.overview || data.plot || data.synopsis || ""
    );

    const episodes = mediaType === "series"
      ? await this.seriesEpisodes(data)
      : await this.movieEpisodes(data, title);

    return {
      title,
      cover: this.resolveUrl(cover),
      desc,
      episodes,
    };
  }

  async watch(url) {
    const packed = String(url || "");
    let type = "";
    let streamUrl = packed;
    let audioTrack = "";

    // Sources generated by detail() carry the media type and, when available,
    // the selected HLS audio playlist. The URL itself is encoded so colons in
    // signed CDN URLs cannot be mistaken for separators.
    const match = packed.match(/^hdghartv:(hls|mp4):([^:]+)(?::(.+))?$/i);
    if (match) {
      type = match[1].toLowerCase();
      streamUrl = this.decodeURIComponentSafe(match[2]);
      audioTrack = match[3] ? this.decodeURIComponentSafe(match[3]) : "";
    }

    streamUrl = this.normaliseUrl(streamUrl);
    if (!/^https?:\/\//i.test(streamUrl)) {
      throw new Error("HDGharTV: invalid stream URL.");
    }

    const isMp4 = type === "mp4" || /\.(?:mp4|webm)(?:$|[?#])/i.test(streamUrl);
    const result = {
      type: isMp4 ? "mp4" : "hls",
      url: streamUrl,
      headers: {
        "User-Agent": USER_AGENT,
        Referer: `${SITE_URL}/`,
        Origin: SITE_URL,
      },
    };
    if (audioTrack && !isMp4) result.audioTrack = audioTrack;
    return result;
  }

  async sitePage(url) {
    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": this.resolveUrl(url),
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          Referer: `${SITE_URL}/`,
          "User-Agent": USER_AGENT,
        },
      });
      return this.asText(response);
    } catch (_) {
      return "";
    }
  }

  scrapeCatalog(html) {
    const source = this.asText(html);
    if (!source || /cloudflare|attention required/i.test(source)) return [];

    const results = [];
    const seen = new Set();
    const anchorRegex = /<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;
    let match;
    while ((match = anchorRegex.exec(source)) !== null) {
      const href = this.decodeHtmlEntities(match[1]);
      const route = href.match(/\/(movie|series)\/([^/?#"']+)/i);
      if (!route) continue;

      const openingTag = match[0].slice(0, match[0].indexOf(">") + 1);
      const content = match[2];
      const imageTag = content.match(/<img\b[^>]*>/i);
      const title = this.cleanText(
        this.htmlAttribute(openingTag, "oldtitle") ||
          this.htmlAttribute(openingTag, "title") ||
          this.htmlAttribute(openingTag, "aria-label") ||
          this.htmlTagText(content, "h1|h2|h3|h4") ||
          (imageTag && this.htmlAttribute(imageTag[0], "alt")) ||
          ""
      );
      if (!title) continue;

      const mediaType = route[1].toLowerCase() === "series" ? "series" : "movie";
      const itemUrl = `${mediaType}:${this.decodeURIComponentSafe(route[2])}`;
      if (seen.has(itemUrl)) continue;
      seen.add(itemUrl);

      const image = imageTag &&
        (this.htmlAttribute(imageTag[0], "data-src") ||
          this.htmlAttribute(imageTag[0], "src") ||
          this.htmlAttribute(imageTag[0], "data-lazy-src"));
      results.push({
        title,
        url: itemUrl,
        cover: this.resolveUrl(this.decodeHtmlEntities(image || "")),
      });
    }

    return results;
  }

  scrapeDetail(html, pageUrl) {
    const source = this.asText(html);
    if (!source || /cloudflare|attention required/i.test(source)) return null;

    const title = this.cleanText(
      this.htmlTagText(source, "h1") ||
        this.htmlTagText(source, "h2") ||
        this.htmlAttributeFromTag(source, "meta", "property", "og:title", "content") ||
        this.htmlTagText(source, "title") ||
        "HDGharTV"
    );
    const cover = this.resolveUrl(
      this.decodeHtmlEntities(
        this.htmlAttributeFromTag(source, "meta", "property", "og:image", "content") ||
          this.htmlAttributeFromTag(source, "img", "itemprop", "image", "src") ||
          this.htmlAttributeFromTag(source, "img", "", "", "data-src") ||
          this.htmlAttributeFromTag(source, "img", "", "", "src") ||
          ""
      ),
      pageUrl
    );
    const desc = this.cleanText(
      this.htmlTagTextByClass(source, "p", "description|overview|plot|synopsis") || ""
    );
    const mediaUrls = this.extractMediaUrls(source).filter((url) =>
      this.isWorkingQuality(url)
    );
    if (!mediaUrls.length) return null;

    return {
      title,
      cover,
      desc,
      episodes: [
        {
          title: "HDGharTV",
          urls: mediaUrls.map((mediaUrl, index) => ({
            name: this.mediaQuality(mediaUrl) || `Server ${index + 1}`,
            url: this.packSource({ url: mediaUrl }),
          })),
        },
      ],
    };
  }

  extractMediaUrls(value) {
    const source = this.asText(value).replace(/\\\//g, "/");
    const urls = [];
    const seen = new Set();
    const add = (candidate) => {
      const url = this.normaliseUrl(candidate);
      if (
        !url ||
        seen.has(url) ||
        !/^https?:\/\//i.test(url) ||
        !/(?:streamraiwind\.stream|\.(?:m3u8|mp4)(?:$|[?#]))/i.test(url)
      ) {
        return;
      }
      seen.add(url);
      urls.push(url);
    };

    const urlRegex = /https?:\/\/[^"'<>\s]+/gi;
    let match;
    while ((match = urlRegex.exec(source)) !== null) add(match[0]);
    return urls;
  }

  mediaQuality(url) {
    const match = String(url || "").match(/(?:2160|1440|1080|720|480|360)p?/i);
    return match ? (/[a-z]/i.test(match[0]) ? match[0] : `${match[0]}p`) : "";
  }

  htmlAttribute(tag, attribute) {
    if (!tag) return "";
    const match = String(tag).match(
      new RegExp(`${attribute}\\s*=\\s*["']([^"']*)["']`, "i")
    );
    return match ? match[1] : "";
  }

  htmlTagText(html, tags) {
    const match = String(html || "").match(
      new RegExp(`<(${tags})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`, "i")
    );
    return match ? this.cleanText(match[2]) : "";
  }

  htmlTagTextByClass(html, tag, classes) {
    const match = String(html || "").match(
      new RegExp(`<${tag}\\b[^>]*class=["'][^"']*(?:${classes})[^"']*["'][^>]*>([\\s\\S]*?)<\\/${tag}>`, "i")
    );
    return match ? this.cleanText(match[1]) : "";
  }

  htmlAttributeFromTag(html, tag, key, value, attribute) {
    const tagRegex = key
      ? new RegExp(`<${tag}\\b[^>]*${key}=["']${value}["'][^>]*>`, "i")
      : new RegExp(`<${tag}\\b[^>]*>`, "i");
    const match = String(html || "").match(tagRegex);
    return match ? this.htmlAttribute(match[0], attribute || "content") : "";
  }

  decodeHtmlEntities(value) {
    return String(value || "")
      .replace(/&amp;/gi, "&")
      .replace(/&quot;/gi, '"')
      .replace(/&#39;|&apos;/gi, "'")
      .replace(/&nbsp;/gi, " ");
  }

  cleanText(value) {
    return this.decodeHtmlEntities(String(value || ""))
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  asText(value) {
    if (typeof value === "string") return value;
    try {
      return JSON.stringify(value || "");
    } catch (_) {
      return String(value || "");
    }
  }

  async api(path) {
    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": `${API_URL}${path}`,
          Accept: "application/json, */*",
          "Accept-Language": "en-US,en;q=0.9",
          Referer: `${SITE_URL}/`,
          "User-Agent": USER_AGENT,
        },
      });

      if (typeof response === "string") {
        try {
          return JSON.parse(response);
        } catch (_) {
          return null;
        }
      }
      return response;
    } catch (_) {
      return null;
    }
  }

  catalogItems(data) {
    if (Array.isArray(data)) return data;
    if (!data || typeof data !== "object") return [];
    for (const key of ["movies", "series", "results", "items", "data"]) {
      if (Array.isArray(data[key])) return data[key];
    }
    return [];
  }

  async toSearchResults(items) {
    const results = [];
    const seen = new Set();

    for (const item of items || []) {
      const id = item && (item._id || item.id);
      const title = this.cleanText(item && (item.title || item.name));
      const mediaType = item && item.mediaType === "series" ? "series" : "movie";
      if (!id || !title) continue;

      const url = `${mediaType}:${id}`;
      if (seen.has(url)) continue;
      seen.add(url);

      let cover = this.imageValue(item);
      if (!cover && item.tmdbId) {
        cover = await this.tmdbImage(item.tmdbId, mediaType);
      }
      results.push({
        title,
        url,
        cover,
      });
    }

    return results;
  }

  async movieEpisodes(data, title) {
    const links = this.activeLinks(data && data.streamingLinks);
    const urls = await this.linkOptions(links, title);
    return urls.length ? [{ title: "HDGharTV", urls }] : [];
  }

  async seriesEpisodes(data) {
    const episodes = [];
    const seasons = Array.isArray(data && data.seasons) ? data.seasons : [];

    for (const season of seasons) {
      const seasonNumber = season && season.seasonNumber != null
        ? season.seasonNumber
        : episodes.length + 1;
      const urls = [];
      const sourceEpisodes = Array.isArray(season && season.episodes)
        ? season.episodes
        : [];

      for (const episode of sourceEpisodes) {
        const episodeNumber = episode && episode.episodeNumber != null
          ? episode.episodeNumber
          : urls.length + 1;
        const episodeTitle = this.cleanText(
          episode && (episode.name || episode.title || `Episode ${episodeNumber}`)
        );
        const links = this.activeLinks(episode && episode.streamingLinks);
        urls.push(...(await this.linkOptions(links, episodeTitle)));
      }

      if (urls.length) {
        episodes.push({
          title: `Season ${seasonNumber}`,
          urls,
        });
      }
    }

    return episodes;
  }

  async linkOptions(links, label) {
    const options = [];

    for (const link of links || []) {
      // At the moment HDGharTV's 480p/720p CDN entries are not playable.
      // Keep them out of the Miru catalogue instead of presenting a link
      // that will only fail after the user selects it.
      if (!this.isWorkingQuality(link.quality)) continue;

      const hls = this.isHlsLink(link);
      const playlist = hls ? await this.fetchPlaylist(link.url) : "";
      const quality = this.cleanText(link.quality || "1080p");
      const tracks = this.parseAudioTracks(playlist, link.url);

      if (tracks.length) {
        for (const track of tracks) {
          options.push({
            name: `${label} · ${quality} · ${track.name}`.trim(),
            url: this.packSource(link, track.url),
          });
        }
      } else {
        const language = this.languageFromLink(link);
        options.push({
          name: `${label} · ${quality}${language ? ` · ${language}` : ""}`.trim(),
          url: this.packSource(link),
        });
      }
    }

    return options;
  }

  activeLinks(links) {
    if (!Array.isArray(links)) return [];
    return links.filter(
      (link) => link && link.url && link.isActive !== false
    );
  }

  isWorkingQuality(quality) {
    const value = String(quality || "");
    // Keep broken lower-quality records out. Direct HLS URLs from the site
    // often do not contain a resolution, so allow the known stream CDN too.
    if (/(?:2160|1440|720|480|360|4k)/i.test(value)) return false;
    return /1080|streamraiwind/i.test(value);
  }

  isHlsLink(link) {
    const type = String(link && link.type || "").toLowerCase();
    return /hls|m3u8/.test(type) || /\.m3u8(?:$|[?#])/i.test(link && link.url || "");
  }

  isPlaylist(value) {
    return /#EXTM3U/i.test(String(value || ""));
  }

  parseAudioTracks(playlist, baseUrl) {
    if (!this.isPlaylist(playlist)) return [];

    const tracks = [];
    const seen = new Set();
    for (const line of String(playlist).split(/\r?\n/)) {
      if (!/#EXT-X-MEDIA:/i.test(line) || !/TYPE\s*=\s*"?AUDIO/i.test(line)) {
        continue;
      }

      const uri = this.hlsAttribute(line, "URI");
      if (!uri) continue;
      const language = this.hlsAttribute(line, "LANGUAGE");
      const trackName = this.hlsAttribute(line, "NAME");
      const name =
        (trackName && !/^default|audio$/i.test(trackName) && trackName) ||
        this.languageName(language) ||
        "Audio";
      const trackUrl = this.resolveUrl(uri, baseUrl);
      if (!trackUrl || seen.has(trackUrl)) continue;

      // The master playlist is the source of truth for alternate audio. Do
      // not make another CDN request here: some valid audio playlists reject
      // a metadata probe even though Miru can load them during playback.
      seen.add(trackUrl);
      tracks.push({
        name: this.cleanText(name || "Audio"),
        url: trackUrl,
      });
    }

    return tracks;
  }

  async fetchPlaylist(url) {
    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": url,
          Accept: "application/vnd.apple.mpegurl, application/x-mpegURL, */*",
          Referer: `${SITE_URL}/`,
          Origin: SITE_URL,
          "User-Agent": USER_AGENT,
        },
      });
      return typeof response === "string" ? response : JSON.stringify(response || "");
    } catch (_) {
      return "";
    }
  }

  hlsAttribute(line, attribute) {
    const match = line.match(
      new RegExp(`${attribute}\\s*=\\s*"([^"]*)"`, "i")
    );
    return match ? this.normaliseUrl(match[1]) : "";
  }

  languageFromLink(link) {
    return this.cleanText(
      link && (link.language || link.lang || link.audio || link.audioLanguage || "")
    );
  }

  languageName(code) {
    const names = {
      bn: "Bengali",
      ben: "Bengali",
      en: "English",
      eng: "English",
      es: "Spanish",
      spa: "Spanish",
      fr: "French",
      fra: "French",
      hi: "Hindi",
      hin: "Hindi",
      id: "Indonesian",
      ind: "Indonesian",
      ja: "Japanese",
      jpn: "Japanese",
      kn: "Kannada",
      kan: "Kannada",
      ko: "Korean",
      kor: "Korean",
      ml: "Malayalam",
      mal: "Malayalam",
      mr: "Marathi",
      mar: "Marathi",
      pa: "Punjabi",
      pan: "Punjabi",
      ta: "Tamil",
      tam: "Tamil",
      te: "Telugu",
      tel: "Telugu",
      ur: "Urdu",
      urd: "Urdu",
    };
    const value = String(code || "").trim();
    const normalized = value.toLowerCase();
    return names[normalized] || names[normalized.split("-")[0]] || value;
  }

  packSource(link, audioTrack = "") {
    const declaredType = String(link.type || "").toLowerCase();
    const sourceUrl = String(link.url || "");
    const isHls =
      /hls|m3u8/.test(declaredType) ||
      /\.m3u8(?:$|[?#])/i.test(sourceUrl);
    const isMp4 = !isHls &&
      (/mp4|webm/.test(declaredType) ||
        /\.(?:mp4|webm)(?:$|[?#])/i.test(sourceUrl));
    const type = isMp4 ? "mp4" : "hls";
    const source = `hdghartv:${type}:${encodeURIComponent(link.url)}`;
    return audioTrack ? `${source}:${encodeURIComponent(audioTrack)}` : source;
  }

  async tmdbImage(id, mediaType) {
    const contentType = mediaType === "series" ? "tv" : "movie";
    const endpoint = `https://api.themoviedb.org/3/${contentType}/${encodeURIComponent(
      id
    )}?api_key=9990db75d12d4ecd4ed84628ebc96403`;

    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": endpoint,
          Accept: "application/json, */*",
          "User-Agent": USER_AGENT,
        },
      });
      const data = typeof response === "string"
        ? JSON.parse(response)
        : response;
      const path = data && (data.poster_path || data.backdrop_path);
      return path
        ? `https://image.tmdb.org/t/p/w500/${String(path).replace(/^\/+/, "")}`
        : "";
    } catch (_) {
      return "";
    }
  }

  imageValue(item) {
    if (!item || typeof item !== "object") return "";

    const direct = this.firstValue([
      item.image,
      item.imageUrl,
      item.poster,
      item.posterUrl,
      item.thumbnail,
      item.thumbnailUrl,
      item.cover,
      item.backdrop,
    ]);
    if (direct) return this.resolveUrl(direct);

    const tmdbPath = this.firstValue([
      item.poster_path,
      item.posterPath,
    ]);
    if (tmdbPath) {
      return `https://image.tmdb.org/t/p/w500/${tmdbPath.replace(/^\/+/, "")}`;
    }
    return "";
  }

  firstValue(values) {
    for (const value of values || []) {
      if (typeof value === "string" && value.trim()) return value.trim();
      if (value && typeof value === "object") {
        const nested = this.firstValue([
          value.url,
          value.src,
          value.path,
          value.original,
        ]);
        if (nested) return nested;
      }
    }
    return "";
  }

  resolveUrl(value, base = SITE_URL) {
    const url = this.normaliseUrl(value);
    if (!url) return "";
    if (/^https?:\/\//i.test(url)) return url;
    if (url.startsWith("//")) return `https:${url}`;

    const baseMatch = String(base || SITE_URL).match(
      /^(https?:\/\/[^/]+)(\/.*)?$/i
    );
    const origin = baseMatch ? baseMatch[1] : SITE_URL;
    if (url.startsWith("/")) return `${origin}${url}`;

    const basePath = (baseMatch && baseMatch[2]) || "/";
    const directory = basePath.endsWith("/")
      ? basePath
      : basePath.replace(/[^/]*$/, "");
    const path = `${directory}${url}`.split("/");
    const cleanPath = [];
    for (const part of path) {
      if (!part || part === ".") continue;
      if (part === "..") cleanPath.pop();
      else cleanPath.push(part);
    }
    return `${origin}/${cleanPath.join("/")}`;
  }

  decodeURIComponentSafe(value) {
    try {
      return decodeURIComponent(value);
    } catch (_) {
      return value;
    }
  }

  normaliseUrl(value) {
    return String(value || "")
      .trim()
      .replace(/\\\//g, "/")
      .replace(/&amp;/gi, "&");
  }

}
