// ==MiruExtension==
// @name         HDGharTV
// @version      v0.0.2
// @author       OshekharO
// @lang         hi
// @license      MIT
// @package      hdghartv
// @type         bangumi
// @icon         https://hdghartv.cc/favicon.ico
// @webSite      https://hdghartv.cc
// @nsfw         false
// ==/MiruExtension==

const SITE_URL = "https://hdghartv.cc";
const API_URL = `${SITE_URL}/api`;
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

export default class extends Extension {
  async latest(page = 1) {
    const pageNumber = Number(page) > 0 ? Number(page) : 1;
    const endpoints = [
      `/movies/public?page=${pageNumber}&limit=24`,
      `/movies?page=${pageNumber}&limit=24`,
      `/trending?page=${pageNumber}&limit=24`,
    ];

    for (const endpoint of endpoints) {
      const data = await this.api(endpoint);
      const movies = this.catalogItems(data);
      if (movies.length) return this.toSearchResults(movies);
    }

    // The public API currently documents search rather than a catalogue
    // endpoint. This keeps the home tab useful if the list endpoint is absent.
    return this.search("a", pageNumber);
  }

  async search(kw, page = 1) {
    const query = String(kw || "").trim();
    if (!query) return [];

    const data = await this.api(`/search?q=${encodeURIComponent(query)}`);
    const items = [
      ...(Array.isArray(data && data.movies) ? data.movies : []).map((item) => ({
        ...item,
        mediaType: "movie",
      })),
      ...(Array.isArray(data && data.series) ? data.series : []).map((item) => ({
        ...item,
        mediaType: "series",
      })),
    ];

    return this.toSearchResults(items);
  }

  async detail(url) {
    const [mediaType, id] = String(url || "").split(":");
    if (!id || !/^(movie|series)$/.test(mediaType)) {
      throw new Error("HDGharTV: invalid catalogue item URL.");
    }

    const data = await this.api(
      `/${mediaType === "series" ? "series" : "movies"}/public/${encodeURIComponent(id)}`
    );
    if (!data || typeof data !== "object") {
      throw new Error("HDGharTV: unable to load the movie details.");
    }

    const title = this.cleanText(data.title || data.name || "HDGharTV");
    const cover = this.firstValue([
      data.poster,
      data.posterUrl,
      data.image,
      data.imageUrl,
      data.thumbnail,
      data.backdrop,
    ]);
    const desc = this.cleanText(
      data.description || data.overview || data.plot || data.synopsis || ""
    );

    const episodes = mediaType === "series"
      ? await this.seriesEpisodes(data)
      : await this.movieEpisodes(data, title);

    return {
      title,
      cover: this.resolveUrl(cover),
      desc,
      episodes,
    };
  }

  async watch(url) {
    const packed = String(url || "");
    let type = "";
    let streamUrl = packed;
    let audioTrack = "";

    // Sources generated by detail() carry the media type and, when available,
    // the selected HLS audio playlist. The URL itself is encoded so colons in
    // signed CDN URLs cannot be mistaken for separators.
    const match = packed.match(/^hdghartv:(hls|mp4):([^:]+)(?::(.+))?$/i);
    if (match) {
      type = match[1].toLowerCase();
      streamUrl = this.decodeURIComponentSafe(match[2]);
      audioTrack = match[3] ? this.decodeURIComponentSafe(match[3]) : "";
    }

    streamUrl = this.normaliseUrl(streamUrl);
    if (!/^https?:\/\//i.test(streamUrl)) {
      throw new Error("HDGharTV: invalid stream URL.");
    }

    const isMp4 = type === "mp4" || /\.(?:mp4|webm)(?:$|[?#])/i.test(streamUrl);
    const result = {
      type: isMp4 ? "mp4" : "hls",
      url: streamUrl,
      // HDGharTV's API returns signed CDN URLs that do not require a
      // referer. Keep a browser user-agent for CDN servers that check it.
      headers: {
        "User-Agent": USER_AGENT,
        Referer: `${SITE_URL}/`,
        Origin: SITE_URL,
      },
    };
    if (audioTrack && !isMp4) result.audioTrack = audioTrack;
    return result;
  }

  async api(path) {
    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": `${API_URL}${path}`,
          Accept: "application/json, */*",
          "Accept-Language": "en-US,en;q=0.9",
          Referer: `${SITE_URL}/`,
          "User-Agent": USER_AGENT,
        },
      });

      if (typeof response === "string") {
        try {
          return JSON.parse(response);
        } catch (_) {
          return null;
        }
      }
      return response;
    } catch (_) {
      return null;
    }
  }

  catalogItems(data) {
    if (Array.isArray(data)) return data;
    if (!data || typeof data !== "object") return [];
    for (const key of ["movies", "series", "results", "items", "data"]) {
      if (Array.isArray(data[key])) return data[key];
    }
    return [];
  }

  toSearchResults(items) {
    const results = [];
    const seen = new Set();

    for (const item of items || []) {
      const id = item && (item._id || item.id);
      const title = this.cleanText(item && (item.title || item.name));
      const mediaType = item && item.mediaType === "series" ? "series" : "movie";
      if (!id || !title) continue;

      const url = `${mediaType}:${id}`;
      if (seen.has(url)) continue;
      seen.add(url);

      const cover = this.firstValue([
        item.image,
        item.imageUrl,
        item.poster,
        item.posterUrl,
        item.thumbnail,
        item.backdrop,
      ]);
      results.push({
        title,
        url,
        cover: this.resolveUrl(cover),
      });
    }

    return results;
  }

  async movieEpisodes(data, title) {
    const links = this.activeLinks(data && data.streamingLinks);
    return [
      {
        title: "HDGharTV",
        urls: await this.linkOptions(links, title),
      },
    ];
  }

  async seriesEpisodes(data) {
    const episodes = [];
    const seasons = Array.isArray(data && data.seasons) ? data.seasons : [];

    for (const season of seasons) {
      const seasonNumber = season && season.seasonNumber != null
        ? season.seasonNumber
        : episodes.length + 1;
      const urls = [];
      const sourceEpisodes = Array.isArray(season && season.episodes)
        ? season.episodes
        : [];

      for (const episode of sourceEpisodes) {
        const episodeNumber = episode && episode.episodeNumber != null
          ? episode.episodeNumber
          : urls.length + 1;
        const episodeTitle = this.cleanText(
          episode && (episode.name || episode.title || `Episode ${episodeNumber}`)
        );
        const links = this.activeLinks(episode && episode.streamingLinks);
        urls.push(...(await this.linkOptions(links, episodeTitle)));
      }

      if (urls.length) {
        episodes.push({
          title: `Season ${seasonNumber}`,
          urls,
        });
      }
    }

    return episodes;
  }

  async linkOptions(links, label) {
    const options = [];

    for (const link of links || []) {
      const quality = this.cleanText(link.quality || "HD");
      const tracks = await this.audioTracks(link);

      if (tracks.length) {
        for (const track of tracks) {
          options.push({
            name: `${label} · ${quality} · ${track.name}`.trim(),
            url: this.packSource(link, track.url),
          });
        }
      } else {
        const language = this.languageFromLink(link);
        options.push({
          name: `${label} · ${quality}${language ? ` · ${language}` : ""}`.trim(),
          url: this.packSource(link),
        });
      }
    }

    return options;
  }

  activeLinks(links) {
    if (!Array.isArray(links)) return [];
    return links.filter(
      (link) => link && link.url && link.isActive !== false
    );
  }

  async audioTracks(link) {
    const linkType = String(link && link.type || "").toLowerCase();
    if (
      /mp4|webm/.test(linkType) ||
      (!/hls|m3u8/.test(linkType) && !/\.m3u8(?:$|[?#])/i.test(link.url || ""))
    ) {
      return [];
    }

    const playlist = await this.fetchPlaylist(link.url);
    if (!playlist) return [];

    const tracks = [];
    const seen = new Set();
    for (const line of playlist.split(/\r?\n/)) {
      if (!/#EXT-X-MEDIA:/i.test(line) || !/TYPE\s*=\s*"?AUDIO/i.test(line)) {
        continue;
      }

      const uri = this.hlsAttribute(line, "URI");
      if (!uri) continue;
      const language = this.hlsAttribute(line, "LANGUAGE");
      const trackName = this.hlsAttribute(line, "NAME");
      const name =
        (trackName && !/^default|audio$/i.test(trackName) && trackName) ||
        this.languageName(language) ||
        "Audio";
      const trackUrl = this.resolveUrl(uri, link.url);
      if (!trackUrl || seen.has(trackUrl)) continue;
      seen.add(trackUrl);
      tracks.push({
        name: this.cleanText(name || "Audio"),
        url: trackUrl,
      });
    }

    return tracks;
  }

  async fetchPlaylist(url) {
    try {
      const response = await this.request("", {
        headers: {
          "Miru-Url": url,
          Accept: "application/vnd.apple.mpegurl, application/x-mpegURL, */*",
          Referer: `${SITE_URL}/`,
          "User-Agent": USER_AGENT,
        },
      });
      return typeof response === "string" ? response : JSON.stringify(response || "");
    } catch (_) {
      return "";
    }
  }

  hlsAttribute(line, attribute) {
    const match = line.match(
      new RegExp(`${attribute}\\s*=\\s*"([^"]*)"`, "i")
    );
    return match ? this.normaliseUrl(match[1]) : "";
  }

  languageFromLink(link) {
    return this.cleanText(
      link && (link.language || link.lang || link.audio || link.audioLanguage || "")
    );
  }

  languageName(code) {
    const names = {
      bn: "Bengali",
      ben: "Bengali",
      en: "English",
      eng: "English",
      es: "Spanish",
      spa: "Spanish",
      fr: "French",
      fra: "French",
      hi: "Hindi",
      hin: "Hindi",
      id: "Indonesian",
      ind: "Indonesian",
      ja: "Japanese",
      jpn: "Japanese",
      kn: "Kannada",
      kan: "Kannada",
      ko: "Korean",
      kor: "Korean",
      ml: "Malayalam",
      mal: "Malayalam",
      mr: "Marathi",
      mar: "Marathi",
      pa: "Punjabi",
      pan: "Punjabi",
      ta: "Tamil",
      tam: "Tamil",
      te: "Telugu",
      tel: "Telugu",
      ur: "Urdu",
      urd: "Urdu",
    };
    const value = String(code || "").trim();
    const normalized = value.toLowerCase();
    return names[normalized] || names[normalized.split("-")[0]] || value;
  }

  packSource(link, audioTrack = "") {
    const declaredType = String(link.type || "").toLowerCase();
    const isMp4 =
      /mp4|webm/.test(declaredType) ||
      /\.(?:mp4|webm)(?:$|[?#])/i.test(String(link.url || ""));
    const type = isMp4 ? "mp4" : "hls";
    const source = `hdghartv:${type}:${encodeURIComponent(link.url)}`;
    return audioTrack ? `${source}:${encodeURIComponent(audioTrack)}` : source;
  }

  firstValue(values) {
    return (values || []).find(
      (value) => typeof value === "string" && value.trim()
    ) || "";
  }

  resolveUrl(value, base = SITE_URL) {
    const url = this.normaliseUrl(value);
    if (!url) return "";
    if (/^https?:\/\//i.test(url)) return url;
    if (url.startsWith("//")) return `https:${url}`;

    const baseMatch = String(base || SITE_URL).match(
      /^(https?:\/\/[^/]+)(\/.*)?$/i
    );
    const origin = baseMatch ? baseMatch[1] : SITE_URL;
    if (url.startsWith("/")) return `${origin}${url}`;

    const basePath = (baseMatch && baseMatch[2]) || "/";
    const directory = basePath.endsWith("/")
      ? basePath
      : basePath.replace(/[^/]*$/, "");
    const path = `${directory}${url}`.split("/");
    const cleanPath = [];
    for (const part of path) {
      if (!part || part === ".") continue;
      if (part === "..") cleanPath.pop();
      else cleanPath.push(part);
    }
    return `${origin}/${cleanPath.join("/")}`;
  }

  decodeURIComponentSafe(value) {
    try {
      return decodeURIComponent(value);
    } catch (_) {
      return value;
    }
  }

  normaliseUrl(value) {
    return String(value || "")
      .trim()
      .replace(/\\\//g, "/")
      .replace(/&amp;/gi, "&");
  }

  cleanText(value) {
    return String(value || "")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }
}
